### ISSUE TITLE
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1128)

### ISSUE THREAD

**Issue by ManBehindMooN** [ManBehindMooN/kodi_plugin_video_srgssr_ch_replay#2]
ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'requests.exceptions.SSLError'>
                                                   Error Contents: HTTPSConnectionPool(host='api.srgssr.ch', port=443): Max retries exceeded with url: /videometadata/v2/tv_shows/alphabetical?bu=srf&characterFilter=%2523&pageSize=unlimited (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1128)')))
                                                   Traceback (most recent call last):
                                                     File "...\Kodi\addons\script.module.urllib3\lib\urllib3\connectionpool.py", line 699, in urlopen
                                                       httplib_response = self._make_request(
                                                     File "...\Kodi\addons\script.module.urllib3\lib\urllib3\connectionpool.py", line 382, in _make_request
                                                       self._validate_conn(conn)
                                                     File "...\Kodi\addons\script.module.urllib3\lib\urllib3\connectionpool.py", line 1010, in _validate_conn
                                                       conn.connect()
                                                     File "...\Kodi\addons\script.module.urllib3\lib\urllib3\connection.py", line 411, in connect
                                                       self.sock = ssl_wrap_socket(
                                                     File "...\Kodi\addons\script.module.urllib3\lib\urllib3\util\ssl_.py", line 428, in ssl_wrap_socket
                                                       ssl_sock = _ssl_wrap_socket_impl(
                                                     File "...\Kodi\addons\script.module.urllib3\lib\urllib3\util\ssl_.py", line 472, in _ssl_wrap_socket_impl
                                                       return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
                                                     File "C:\Program Files\Kodi\system\python\Lib\ssl.py", line 500, in wrap_socket
                                                       return self.sslsocket_class._create(
                                                     File "C:\Program Files\Kodi\system\python\Lib\ssl.py", line 1040, in _create
                                                       self.do_handshake()
                                                     File "C:\Program Files\Kodi\system\python\Lib\ssl.py", line 1309, in do_handshake
                                                       self._sslobj.do_handshake()
                                                   ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1128)
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "...\Kodi\addons\script.module.requests\lib\requests\adapters.py", line 439, in send
                                                       resp = conn.urlopen(
                                                     File "...\Kodi\addons\script.module.urllib3\lib\urllib3\connectionpool.py", line 755, in urlopen
                                                       retries = retries.increment(
                                                     File "...\Kodi\addons\script.module.urllib3\lib\urllib3\util\retry.py", line 574, in increment
                                                       raise MaxRetryError(_pool, url, error or ResponseError(cause))
                                                   urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.srgssr.ch', port=443): Max retries exceeded with url: /videometadata/v2/tv_shows/alphabetical?bu=srf&characterFilter=%2523&pageSize=unlimited (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1128)')))
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "...\Kodi\addons\plugin.video.srgssr_ch_replay\addon.py", line 362, in <module>
                                                       list_tv_shows(channel, letter)
                                                     File "...\Kodi\addons\plugin.video.srgssr_ch_replay\addon.py", line 74, in list_tv_shows
                                                       _query_tv_shows(channel, path, query, "showList")
                                                     File "...\Kodi\addons\plugin.video.srgssr_ch_replay\addon.py", line 78, in _query_tv_shows
                                                       response = _srg_get(path, query=query)
                                                     File "...\Kodi\addons\plugin.video.srgssr_ch_replay\addon.py", line 172, in _srg_get
                                                       data = _get_with_token(path, query)
                                                     File "...\Kodi\addons\plugin.video.srgssr_ch_replay\addon.py", line 167, in _get_with_token
                                                       r = _srg_api_get_simple(path, bearer=token, query=query, exp_code=[200, 203])
                                                     File "...\Kodi\addons\plugin.video.srgssr_ch_replay\addon.py", line 138, in _srg_api_get_simple
                                                       return _http_request(SRG_API_HOST, 'GET', path, query, headers, None, exp_code)
                                                     File "...\Kodi\addons\plugin.video.srgssr_ch_replay\addon.py", line 193, in _http_request
                                                       res = requests.request(method, uri, params=query, headers=headers, json=body_dict)
                                                     File "...\Kodi\addons\script.module.requests\lib\requests\api.py", line 61, in request
                                                       return session.request(method=method, url=url, **kwargs)
                                                     File "...\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 542, in request
                                                       resp = self.send(prep, **send_kwargs)
                                                     File "...\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 655, in send
                                                       r = adapter.send(request, **kwargs)
                                                     File "...\Kodi\addons\script.module.requests\lib\requests\adapters.py", line 514, in send
                                                       raise SSLError(e, request=request)
                                                   requests.exceptions.SSLError: HTTPSConnectionPool(host='api.srgssr.ch', port=443): Max retries exceeded with url: /videometadata/v2/tv_shows/alphabetical?bu=srf&characterFilter=%2523&pageSize=unlimited (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1128)')))
                                                   -->End of Python script error report<--
                                                   
2021-10-17 20:37:19.921 T:4880     INFO <general>: Python interpreter stopped
2021-10-17 20:37:19.927 T:4232    ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.srgssr_ch_replay/?channel=srf&letter=%23&mode=listTvShowsByLetter
2021-10-17 20:37:19.945 T:5624    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.srgssr_ch_replay/?channel=srf&letter=%23&mode=listTvShowsByLetter) failed

**Comment by ManBehindMooN** [comment]
Tested with Kodi 19.0 and 19.2 and it seems to work again.
