### ISSUE TITLE
Fail to view show. After that fail to list folder content.

### ISSUE THREAD

**Issue by PJaros** [ManBehindMooN/kodi_plugin_video_srgssr_ch_replay#7]
I'm running Ubuntu 18.04, Kodi 19.4 and installed "Unofficial SRG SSR Replay" 3.0.3 from the Repository. I've gone to https://developer.srgssr.ch/user/me/apps and fetched a SRG-SSR-PUBLIC-API-V2 Key and Secret as instructed and copy&pasted them through YATSE App from my Android phone.

After installing the add-on I am able to browse the alphabet Folders. Going to "t" and listing the content of "t". After trying to watch "Taggesschau" I got a error saying I should look into the logs. After that going into "t" woul'd let me browse through the show.

I am a python developer. But I don't know how Kodi-Addons work so my knowledge isn't of much use here. 

This is the error log part where I try to watch "Taggesschau". Any suggestions are creatly appriciated:
```
2022-03-19 21:45:59.277 T:24258   DEBUG <general>: Keyboard: scancode: 0x24, sym: 0x13, unicode: 0x000d, modifier: 0x0
2022-03-19 21:45:59.560 T:24258   DEBUG <general>: Keyboard: scancode: 0x24, sym: 0x13, unicode: 0x0000, modifier: 0x0
2022-03-19 21:45:59.560 T:24258   DEBUG <general>: HandleKey: return (0xf00d) pressed, action is Select
2022-03-19 21:45:59.560 T:24258   DEBUG <general>: Activating window ID: 10025
2022-03-19 21:45:59.886 T:24258   DEBUG <general>: ------ Window Deinit (AddonBrowser.xml) ------
2022-03-19 21:45:59.886 T:24258   DEBUG <general>: FreeVisualisation() done
2022-03-19 21:45:59.886 T:24258   DEBUG <general>: ------ Window Deinit (DialogAddonInfo.xml) ------
2022-03-19 21:45:59.893 T:24258   DEBUG <general>: ------ Window Init (MyVideoNav.xml) ------
2022-03-19 21:45:59.895 T:24258   ERROR <general>: Control 50 in window 10025 has been asked to focus, but it can't
2022-03-19 21:45:59.927 T:24258   DEBUG <general>: CGUIMediaWindow::GetDirectory (plugin://plugin.video.srgssr_ch_replay/?channel=srf&letter=t&mode=listTvShowsByLetter)
2022-03-19 21:45:59.927 T:24258   DEBUG <general>:   ParentPath = [plugin://plugin.video.srgssr_ch_replay/?channel=srf&letter=t&mode=listTvShowsByLetter]
2022-03-19 21:45:59.928 T:24258   DEBUG <general>: Loading items: 13, directory: plugin://plugin.video.srgssr_ch_replay/?channel=srf&letter=t&mode=listTvShowsByLetter sort method: 0, ascending: false
2022-03-19 21:45:59.940 T:25769   DEBUG <general>: CAddonDatabase::SetLastUsed[plugin.video.srgssr_ch_replay] took 12 ms
2022-03-19 21:45:59.942 T:26150   DEBUG <general>: Thread BackgroundLoader start, auto delete: false
2022-03-19 21:45:59.946 T:26150   DEBUG <general>: Thread BackgroundLoader 139624712607488 terminating
2022-03-19 21:45:59.947 T:25769   DEBUG <general>: ffmpeg[0x563206bac790X]: [image2] Custom AVIOContext makes no sense and will be ignored with AVFMT_NOFILE format.
2022-03-19 21:46:00.126 T:24588   DEBUG <CWebserver[2345]>: request received for /jsonrpc?JSONRPC.Ping
2022-03-19 21:46:00.136 T:24588   DEBUG <CWebserver[2345]>: request received for /jsonrpc?Application.GetProperties
2022-03-19 21:46:00.145 T:24588   DEBUG <CWebserver[2345]>: request received for /jsonrpc?Player.GetActivePlayers
2022-03-19 21:46:00.329 T:25609   DEBUG <CWebserver[2345]>: request received for /jsonrpc
2022-03-19 21:46:00.997 T:24258   DEBUG <general>: Skipped 1 duplicate messages..
2022-03-19 21:46:00.997 T:24258   DEBUG <general>: CGLContextEGL::SwapBuffers: sync check blocking
2022-03-19 21:46:01.010 T:24258   DEBUG <general>: CGLContextEGL::SwapBuffers: sync sleep: 13269
2022-03-19 21:46:01.281 T:24258   DEBUG <general>: CGLContextEGL::SwapBuffers: sync check blocking
2022-03-19 21:46:01.293 T:24258   DEBUG <general>: CGLContextEGL::SwapBuffers: sync sleep: 12422
2022-03-19 21:46:01.431 T:24258   DEBUG <general>: CGLContextEGL::SwapBuffers: sync check blocking
2022-03-19 21:46:01.443 T:24258   DEBUG <general>: CGLContextEGL::SwapBuffers: sync sleep: 12070
2022-03-19 21:46:01.681 T:24258   DEBUG <general>: Keyboard: scancode: 0x24, sym: 0x13, unicode: 0x000d, modifier: 0x0
2022-03-19 21:46:01.765 T:24258   DEBUG <general>: Keyboard: scancode: 0x24, sym: 0x13, unicode: 0x0000, modifier: 0x0
2022-03-19 21:46:01.765 T:24258   DEBUG <general>: HandleKey: return (0xf00d) pressed, action is Select
2022-03-19 21:46:01.766 T:24258   DEBUG <general>: CGUIMediaWindow::GetDirectory (plugin://plugin.video.srgssr_ch_replay/?channel=srf&mode=listEpisodes&numberOfEpisodes=16609&showbackground=https%3a%2f%2fws.
srf.ch%2fasset%2fimage%2faudio%2f7e18e733-622b-4bd5-9323-971239e49844%2fWEBVISUAL%2f1607950376.jpg&url=ff969c14-c5a7-44ab-ab72-14d4c9e427a9&urn=urn%3asrf%3ashow%3atv%3aff969c14-c5a7-44ab-ab72-14d4c9e427a9)
2022-03-19 21:46:01.766 T:24258   DEBUG <general>:   ParentPath = [plugin://plugin.video.srgssr_ch_replay/?channel=srf&letter=t&mode=listTvShowsByLetter]
2022-03-19 21:46:01.767 T:26157   DEBUG <general>: Thread waiting start, auto delete: false
2022-03-19 21:46:01.783 T:25769   DEBUG <general>: CAddonDatabase::SetLastUsed[plugin.video.srgssr_ch_replay] took 17 ms
2022-03-19 21:46:01.784 T:26157   DEBUG <general>: StartScript - calling plugin Unofficial SRG SSR Replay('plugin://plugin.video.srgssr_ch_replay/','17','?channel=srf&mode=listEpisodes&numberOfEpisodes=16609
&showbackground=https%3a%2f%2fws.srf.ch%2fasset%2fimage%2faudio%2f7e18e733-622b-4bd5-9323-971239e49844%2fWEBVISUAL%2f1607950376.jpg&url=ff969c14-c5a7-44ab-ab72-14d4c9e427a9&urn=urn%3asrf%3ashow%3atv%3aff969c
14-c5a7-44ab-ab72-14d4c9e427a9','resume:false')
2022-03-19 21:46:01.784 T:26158   DEBUG <general>: Thread LanguageInvoker start, auto delete: false
2022-03-19 21:46:01.784 T:26158    INFO <general>: initializing python engine.
2022-03-19 21:46:01.784 T:26158   DEBUG <general>: CPythonInvoker(21, /home/madmike/.kodi/addons/plugin.video.srgssr_ch_replay/addon.py): start processing
2022-03-19 21:46:01.867 T:24258   DEBUG <general>: ------ Window Init (DialogBusy.xml) ------
2022-03-19 21:46:01.934 T:26158   DEBUG <general>: -->Python Interpreter Initialized<--
2022-03-19 21:46:01.934 T:26158   DEBUG <general>: 
                                                   
2022-03-19 21:46:01.934 T:26158   DEBUG <general>: CPythonInvoker(21, /home/madmike/.kodi/addons/plugin.video.srgssr_ch_replay/addon.py): the source file to load is "/home/madmike/.kodi/addons/plugin.video.s
rgssr_ch_replay/addon.py"
2022-03-19 21:46:01.935 T:26158   DEBUG <general>: CPythonInvoker(21, /home/madmike/.kodi/addons/plugin.video.srgssr_ch_replay/addon.py): setting the Python path to /home/madmike/.kodi/addons/plugin.video.srgssr_ch_replay:/home/madmike/.kodi/addons/script.module.certifi/lib:/home/madmike/.kodi/addons/script.module.chardet/lib:/home/madmike/.kodi/addons/script.module.idna/lib:/home/madmike/.kodi/addons/script.module.requests/lib:/home/madmike/.kodi/addons/script.module.urllib3/lib:/usr/lib/python36.zip:/usr/lib/python3.6:/usr/lib/python3.6/lib-dynload:/home/madmike/.local/lib/python3.6/site-packages:/usr/local/lib/python3.6/dist-packages:/usr/lib/python3/dist-packages
2022-03-19 21:46:01.935 T:26158   DEBUG <general>: CPythonInvoker(21, /home/madmike/.kodi/addons/plugin.video.srgssr_ch_replay/addon.py): entering source directory /home/madmike/.kodi/addons/plugin.video.srgssr_ch_replay
2022-03-19 21:46:01.935 T:26158   DEBUG <general>: CPythonInvoker(21, /home/madmike/.kodi/addons/plugin.video.srgssr_ch_replay/addon.py): instantiating addon using automatically obtained id of "plugin.video.srgssr_ch_replay" dependent on version 3.0.0 of the xbmc.python api
2022-03-19 21:46:01.961 T:25609   DEBUG <CWebserver[2345]>: request received for /jsonrpc
2022-03-19 21:46:01.963 T:24258   DEBUG <general>: CGLContextEGL::SwapBuffers: sync check blocking
2022-03-19 21:46:01.974 T:25609   DEBUG <CWebserver[2345]>: request received for /jsonrpc
2022-03-19 21:46:01.977 T:24258   DEBUG <general>: CGLContextEGL::SwapBuffers: sync sleep: 13550
2022-03-19 21:46:02.128 T:24588   DEBUG <CWebserver[2345]>: request received for /jsonrpc?JSONRPC.Ping
2022-03-19 21:46:02.138 T:24342   DEBUG <CWebserver[2345]>: Skipped 1 duplicate messages..
2022-03-19 21:46:02.138 T:24342   DEBUG <CWebserver[2345]>: request received for /jsonrpc?Application.GetProperties
2022-03-19 21:46:02.150 T:24342   DEBUG <CWebserver[2345]>: Skipped 1 duplicate messages..
2022-03-19 21:46:02.150 T:24342   DEBUG <CWebserver[2345]>: request received for /jsonrpc?Player.GetActivePlayers
2022-03-19 21:46:02.500 T:26158   DEBUG <CAddonSettings[plugin.video.srgssr_ch_replay]>: Skipped 1 duplicate messages..
2022-03-19 21:46:02.500 T:26158   DEBUG <CAddonSettings[plugin.video.srgssr_ch_replay]>: trying to load setting definitions from old format...
2022-03-19 21:46:02.501 T:26158   DEBUG <CSettingsManager>: requested setting (srgssrToken) was not found.
2022-03-19 21:46:02.501 T:26158   DEBUG <CSettingsManager>: requested setting (srgssrTokenTS) was not found.
2022-03-19 21:46:02.503 T:26158   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: type object 'datetime.datetime' has no attribute 'fromisoformat'
                                                   Traceback (most recent call last):
                                                     File "/home/madmike/.kodi/addons/plugin.video.srgssr_ch_replay/addon.py", line 415, in <module>
                                                       main()
                                                     File "/home/madmike/.kodi/addons/plugin.video.srgssr_ch_replay/addon.py", line 401, in main
                                                       list_episodes(bu, url, showbackground, page, numberOfEpisodes, nextParam)
                                                     File "/home/madmike/.kodi/addons/plugin.video.srgssr_ch_replay/addon.py", line 122, in list_episodes
                                                       response = _srg_get(path, query=query)
                                                     File "/home/madmike/.kodi/addons/plugin.video.srgssr_ch_replay/addon.py", line 197, in _srg_get
                                                       data = _get_with_token(path, query)
                                                     File "/home/madmike/.kodi/addons/plugin.video.srgssr_ch_replay/addon.py", line 190, in _get_with_token
                                                       token = _srg_api_auth_token(tokenPrefix)
                                                     File "/home/madmike/.kodi/addons/plugin.video.srgssr_ch_replay/addon.py", line 163, in _srg_api_auth_token
                                                       delta_ts = datetime.datetime.utcnow() - datetime.datetime.fromisoformat(token_ts)
                                                   AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'
                                                   -->End of Python script error report<--
                                                   
2022-03-19 21:46:02.503 T:26158   DEBUG <general>: onExecutionDone(21, /home/madmike/.kodi/addons/plugin.video.srgssr_ch_replay/addon.py)
2022-03-19 21:46:02.511 T:24258   DEBUG <general>: ------ Window Init (DialogNotification.xml) ------
2022-03-19 21:46:02.635 T:26158    INFO <general>: Python interpreter stopped
2022-03-19 21:46:02.635 T:26158   DEBUG <general>: Thread LanguageInvoker 139624704214784 terminating
2022-03-19 21:46:02.648 T:26157   ERROR <general>: GetDirectory - Error getting plugin://plugin.video.srgssr_ch_replay/?channel=srf&mode=listEpisodes&numberOfEpisodes=16609&showbackground=https%3a%2f%2fws.srf.ch%2fasset%2fimage%2faudio%2f7e18e733-622b-4bd5-9323-971239e49844%2fWEBVISUAL%2f1607950376.jpg&url=ff969c14-c5a7-44ab-ab72-14d4c9e427a9&urn=urn%3asrf%3ashow%3atv%3aff969c14-c5a7-44ab-ab72-14d4c9e427a9
2022-03-19 21:46:02.648 T:26157   DEBUG <general>: Thread waiting 139627323582208 terminating
2022-03-19 21:46:02.660 T:24258   DEBUG <general>: ------ Window Deinit (DialogBusy.xml) ------
2022-03-19 21:46:02.660 T:24258   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.srgssr_ch_replay/?channel=srf&mode=listEpisodes&numberOfEpisodes=16609&showbackground=https%3a%2f%2fws.srf.ch%2fasset%2fimage%2faudio%2f7e18e733-622b-4bd5-9323-971239e49844%2fWEBVISUAL%2f1607950376.jpg&url=ff969c14-c5a7-44ab-ab72-14d4c9e427a9&urn=urn%3asrf%3ashow%3atv%3aff969c14-c5a7-44ab-ab72-14d4c9e427a9) failed
2022-03-19 21:46:02.660 T:24258   DEBUG <general>: CGUIMediaWindow::GetDirectory (plugin://plugin.video.srgssr_ch_replay/?channel=srf&letter=t&mode=listTvShowsByLetter)
2022-03-19 21:46:02.660 T:24258   DEBUG <general>:   ParentPath = [plugin://plugin.video.srgssr_ch_replay/?channel=srf&mode=chooseTvShowOption]
2022-03-19 21:46:02.661 T:24258   DEBUG <general>: Loading items: 13, directory: plugin://plugin.video.srgssr_ch_replay/?channel=srf&letter=t&mode=listTvShowsByLetter sort method: 0, ascending: false
2022-03-19 21:46:02.673 T:25767   DEBUG <general>: CAddonDatabase::SetLastUsed[plugin.video.srgssr_ch_replay] took 13 ms
2022-03-19 21:46:02.675 T:26161   DEBUG <general>: Thread BackgroundLoader start, auto delete: false
2022-03-19 21:46:02.679 T:26161   DEBUG <general>: Thread BackgroundLoader 139624712607488 terminating
2022-03-19 21:46:03.127 T:24342   DEBUG <CWebserver[2345]>: request received for /jsonrpc?JSONRPC.Ping
2022-03-19 21:46:03.141 T:24588   DEBUG <CWebserver[2345]>: Skipped 1 duplicate messages..
2022-03-19 21:46:03.141 T:24588   DEBUG <CWebserver[2345]>: request received for /jsonrpc?Application.GetProperties
```

**Comment by PJaros** [comment]
The reason is `datetime.datetime.fromisoformat()` [was introduced with python 3.7](https://docs.python.org/3/library/datetime.html#datetime.date.fromisoformat) but Ubuntu 18.04 apparently comes with Python 2.7.17 and Python 3.6.9.
I'm going to try to replace kodi_plugin_video_srgssr_ch_replay/plugin.video.srgssr_ch_replay/addon.py:163
`datetime.datetime.fromisoformat(token_ts)` with `datetime.datetime.strptime(d["Initialized"], r"%Y-%m-%dT%H:%M:%S.%f")` as it was done in this [patch from another project](https://github.com/precice/EventTimings/commit/7cf5b06693bef98486a5391e05358a543fab4e3e).

**Comment by PJaros** [comment]
I've changed addon.py:163 to `        delta_ts = datetime.datetime.utcnow() - datetime.datetime.strptime(token_ts, r"%Y-%m-%dT%H:%M:%S.%f")` and created a new ZIP-File. Now the error is the following:
```
2022-03-19 22:51:05.060 T:10841   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: attribute of type 'NoneType' is not callable
                                                   Traceback (most recent call last):
                                                     File "/home/madmike/.kodi/addons/plugin.video.srgssr_ch_replay/addon.py", line 415, in <module>
                                                       main()
                                                     File "/home/madmike/.kodi/addons/plugin.video.srgssr_ch_replay/addon.py", line 401, in main
                                                       list_episodes(bu, url, showbackground, page, numberOfEpisodes, nextParam)
                                                     File "/home/madmike/.kodi/addons/plugin.video.srgssr_ch_replay/addon.py", line 122, in list_episodes
                                                       response = _srg_get(path, query=query)
                                                     File "/home/madmike/.kodi/addons/plugin.video.srgssr_ch_replay/addon.py", line 197, in _srg_get
                                                       data = _get_with_token(path, query)
                                                     File "/home/madmike/.kodi/addons/plugin.video.srgssr_ch_replay/addon.py", line 190, in _get_with_token
                                                       token = _srg_api_auth_token(tokenPrefix)
                                                     File "/home/madmike/.kodi/addons/plugin.video.srgssr_ch_replay/addon.py", line 163, in _srg_api_auth_token
                                                       delta_ts = datetime.datetime.utcnow() - datetime.datetime.strptime(token_ts, r"%Y-%m-%dT%H:%M:%S.%f")
                                                   TypeError: attribute of type 'NoneType' is not callable
                                                   -->End of Python script error report<--
```
I clearly don't know enough about what I'm doing here ...

**Comment by ManBehindMooN** [comment]
Hi @PJaros,
I have tested the plugin with Ubuntu 20.04.4 LTS and Kodi 19.4 and it just works perfectly fine (out of the box; I have not bothered to check the Python version). Ubuntu 18.04 and Python 3.6 is rather old and we develop our add-on with at least Python 3.8 and here is why:
* All platforms except Linux currently have 3.8.5+ embedded.
* Linux uses whatever the system version is
We test and develop our add-on with the version the embedded version (Android, Windows) and from Linux Users we expect to have at least that version. Sorry to say but you have to upgrade at least your Python version.

**Comment by PJaros** [comment]
@ManBehindMooN I was able to patch the code to work with python 3.6 (well, at least for this bug). If you are interested I give you the code... or I can produce a pull-request.... I just first need to find out how to do pull-requests. ;-)

**Comment by ManBehindMooN** [comment]
Hi @PJaros,
Just paste the code snippet in this issue as a documentation. Don't bother with a PR as I do not see much use to support Python 3.6. I quickly tested the add-on with LibreELEC and even there it works out of the box.

**Comment by PJaros** [comment]
I've created a fork to stay in sync.

This is the diff:
```
diff --git a/plugin.video.srgssr_ch_replay/addon.py b/plugin.video.srgssr_ch_replay/addon.py                                                                                                                   
index cd865c2..6863a7d 100644                                                                                                                                                                                  
--- a/plugin.video.srgssr_ch_replay/addon.py                                                                                                                                                                   
+++ b/plugin.video.srgssr_ch_replay/addon.py                                                                                                                                                                   
@@ -157,10 +157,26 @@ def _srg_api_get_simple(path, *, query=None, bearer, exp_code=None):                                                                                                                     
     return _http_request(SRG_API_HOST, 'GET', path, query, headers, None, exp_code)                                                                                                                           
                                                                                                                                                                                                               
                                                                                                                                                                                                               
+def _convert_string_to_datetime(string_date, format):                                                                                                                                                         
+    """                                                                                                                                                                                                       
+    Calling datetime.datetime.strptime(...) can result in a "TypeError attribute of type 'NoneType' is not callable"-Error                                                                                    
+    Workaround from: https://bugs.python.org/issue27400#msg269379                                                                                                                                             
+    """                                                                                                                                                                                                       
+    try:                                                                                                                                                                                                      
+        conv_date = datetime.datetime.strptime(string_date, format)                                                                                                                                           
+    except TypeError:                                                                                                                                                                                         
+        import time                                                                                                                                                                                           
+        conv_date = datetime.datetime.fromtimestamp(time.mktime(time.strptime(string_date, format)))                                                                                                          
+    return conv_date                                                                                                                                                                                          
+                                                                                                                                                                                                              
+                                                                                                                                                                                                              
 def _srg_api_auth_token(tokenPrefix):                                                                                                                                                                         
     token_ts = addon.getSetting(f'srgssr{tokenPrefix}TokenTS')                                                                                                                                                
     if token_ts:                                                                                                                                                                                              
-        delta_ts = datetime.datetime.utcnow() - datetime.datetime.fromisoformat(token_ts)                                                                                                                     
+        # Example token_ts content: "2022-03-19T20:44:33.171996"                                                                                                                                              
+        dt_token_ts = _convert_string_to_datetime(token_ts, "%Y-%m-%dT%H:%M:%S.%f")                                                                                                                           
+        dt_now = datetime.datetime.utcnow()                                                                                                                                                                   
+        delta_ts = dt_now - dt_token_ts                                                                                                                                                                       
         token = addon.getSetting(f'srgssr{tokenPrefix}Token')                                                                                                                                                 
         if delta_ts < datetime.timedelta(days=25) and token:                                                                                                                                                  
             return token                                                                                                                                                                                      
```

**Comment by ManBehindMooN** [comment]
@PJaros, Thank you! Is there a particularly reason you can't use a newer Python version?

**Comment by PJaros** [comment]
Installing a new python version isn't dificult. I did it. But Kodi won't use it. I did the following:

```bash
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt install python3.8
```
After that I had the following environment:
```bash
$ python3 -V
Python 3.6.9
$ which python3
/usr/bin/python3
$ which python3.6
/usr/bin/python3.6
$ ls -alh /usr/bin/python3
lrwxrwxrwx 1 root root 9 Okt 25  2018 /usr/bin/python3 -> python3.6
$ ls -alh /usr/bin/python3.6
-rwxr-xr-x 2 root root 4.4M Dez  8 22:08 /usr/bin/python3.6
$ /usr/bin/python3.8 -V
Python 3.8.13
```
I've used to `update-alternatives` to set python3.8 as the default python3. But kodi won't use it:
```bash
sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 2
sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1
```
Also, one needs to be **very** carefull messing with python on Linux. A messed up python setup can give you a unbootable system. So I've removed the python3.8 from the alternative list.
```bash
sudo update-alternatives --remove python3 /usr/bin/python3.6
```

**Comment by ManBehindMooN** [comment]
@meierfra do you have an advice? how do you handle on your Linux system?

**Comment by PJaros** [comment]
I've created a [PR](https://github.com/ManBehindMooN/kodi_plugin_video_srgssr_ch_replay/pull/8) to see how/if this works. Feel free to reject it.

**Comment by meierfra** [comment]
> @meierfra do you have an advice? how do you handle on your Linux system?

I had a short look into it, and I did not see a way to change the python-interpreter used by Kodi on Linux e.g by setting an environment variable.

Personally I find it strange, that only on Linux Kodi does not use the built-in Python interpreter. Maybe this could be considered a bug in Kodi for Linux, since on the Kodi Add-on wiki page [1] it only states "Kodi includes a built-in Python interpreter that allows users to develop add-ons ....". So one could assume this is the case for all plattforms.

[1] https://kodi.wiki/view/About_Add-ons

**Comment by ManBehindMooN** [comment]
This post mentions another behavior:
![image](https://user-images.githubusercontent.com/20797220/159583901-1f1bb403-d724-4016-aab7-d36639e10566.png)
https://forum.kodi.tv/showthread.php?tid=361850
